export interface BordroItem {
  id: string;
  company_id: string;
  employee_id: string;
  period: string;
  sicil_no: string;
  tc_no: string;
  brut_maas: number;
  medeni_durum: 'bekar' | 'evli';
  cocuk_sayisi: number;
  engelli_durumu: 'yok' | 'birinci' | 'ikinci' | 'ucuncu';
  temel_kazanc: number;
  yol_parasi: number;
  gida_yardimi: number;
  cocuk_yardimi: number;
  diger_kazanclar: number;
  fazla_mesai: number;
  fazla_mesai_saat_50: number;
  fazla_mesai_saat_100: number;
  fazla_mesai_tutar: number;
  haftalik_tatil: number;
  genel_tatil: number;
  yillik_izin_ucreti: number;
  ikramiye: number;
  prim: number;
  servis_ucreti: number;
  temsil_etiket: number;
  gelir_vergisi: number;
  damga_vergisi: number;
  sgk_isci_payi: number;
  issizlik_sigortasi: number;
  sendika_aidat: number;
  avans: number;
  diger_kesintiler: number;
  engelli_indirimi: number;
  kidem_tazminati: number;
  ihbar_tazminati: number;
  toplam_kazanc: number;
  toplam_kesinti: number;
  net_maas: number;
  kumulatif_vergi_matrahi: number;
  asgari_ucret_gelir_vergisi_istisnasi: number;
  asgari_ucret_damga_vergisi_istisnasi: number;
  sgk_isveren_payi: number;
  issizlik_isveren_payi: number;
  sgk_isveren_indirimi: number;
  sgk_isveren_indirim_orani: number;
  yillik_toplam_kazanc: number;
  yillik_toplam_kesinti: number;
  yillik_toplam_net: number;
  aciklama: string;
  created_at: string;
  updated_at: string;
  // joined relation
  employees?: { name: string; department: string; tc_no?: string; sicil_no?: string };
}
